// <auto-generated />
using System;
using BuyOrderCalc.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuyOrderCalc.EntityFramework.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("BuyOrderCalc.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("MarketPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplyTypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            MarketPrice = 2,
                            Name = "Tritanium",
                            Quantity = 17450000,
                            ReorderLevel = 18742950,
                            SupplyTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            MarketPrice = 18,
                            Name = "Pyerite",
                            Quantity = 6950000,
                            ReorderLevel = 5312610,
                            SupplyTypeId = 2,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            MarketPrice = 32,
                            Name = "Mexallon",
                            Quantity = 2290000,
                            ReorderLevel = 1665210,
                            SupplyTypeId = 3,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            MarketPrice = 110,
                            Name = "Isogen",
                            Quantity = 170000,
                            ReorderLevel = 284720,
                            SupplyTypeId = 3,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            MarketPrice = 1000,
                            Name = "Nocxium",
                            Quantity = 130000,
                            ReorderLevel = 67810,
                            SupplyTypeId = 2,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            MarketPrice = 225,
                            Name = "Zydrine",
                            Quantity = 5413,
                            ReorderLevel = 0,
                            SupplyTypeId = 4,
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("BuyOrderCalc.Domain.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Mineral"
                        },
                        new
                        {
                            Id = 2,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Planetary"
                        },
                        new
                        {
                            Id = 3,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Debt"
                        },
                        new
                        {
                            Id = 4,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Wallet"
                        });
                });

            modelBuilder.Entity("BuyOrderCalc.Domain.SupplyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CorpCreditPercent")
                        .HasColumnType("REAL");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PricePercentModifier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SupplyType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorpCreditPercent = 2.0,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "High",
                            PricePercentModifier = 80
                        },
                        new
                        {
                            Id = 2,
                            CorpCreditPercent = 3.0,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Low",
                            PricePercentModifier = 90
                        },
                        new
                        {
                            Id = 3,
                            CorpCreditPercent = 4.0,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Emergency",
                            PricePercentModifier = 105
                        },
                        new
                        {
                            Id = 4,
                            CorpCreditPercent = 0.0,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Unwanted",
                            PricePercentModifier = 1
                        });
                });

            modelBuilder.Entity("BuyOrderCalc.Domain.Item", b =>
                {
                    b.HasOne("BuyOrderCalc.Domain.SupplyType", "SupplyType")
                        .WithMany()
                        .HasForeignKey("SupplyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuyOrderCalc.Domain.ItemType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
